/* soapH.h
   Generated by gSOAP 2.7.9b from SrbStorageWS.h
   Copyright(C) 2000-2006, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
#ifndef WITH_NOIDREF
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, int*);
#endif

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE__ns5__fileInfo
#define SOAP_TYPE__ns5__fileInfo (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns5__fileInfo(struct soap*, const char*, int, const _ns5__fileInfo *, const char*);
SOAP_FMAC3 _ns5__fileInfo * SOAP_FMAC4 soap_get__ns5__fileInfo(struct soap*, _ns5__fileInfo *, const char*, const char*);
SOAP_FMAC3 _ns5__fileInfo * SOAP_FMAC4 soap_in__ns5__fileInfo(struct soap*, const char*, _ns5__fileInfo *, const char*);
SOAP_FMAC5 _ns5__fileInfo * SOAP_FMAC6 soap_new__ns5__fileInfo(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns5__fileInfo(struct soap*, _ns5__fileInfo*);
SOAP_FMAC3 _ns5__fileInfo * SOAP_FMAC4 soap_instantiate__ns5__fileInfo(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns5__fileInfo(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns5__SrbUpload
#define SOAP_TYPE__ns5__SrbUpload (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns5__SrbUpload(struct soap*, const char*, int, const _ns5__SrbUpload *, const char*);
SOAP_FMAC3 _ns5__SrbUpload * SOAP_FMAC4 soap_get__ns5__SrbUpload(struct soap*, _ns5__SrbUpload *, const char*, const char*);
SOAP_FMAC3 _ns5__SrbUpload * SOAP_FMAC4 soap_in__ns5__SrbUpload(struct soap*, const char*, _ns5__SrbUpload *, const char*);
SOAP_FMAC5 _ns5__SrbUpload * SOAP_FMAC6 soap_new__ns5__SrbUpload(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns5__SrbUpload(struct soap*, _ns5__SrbUpload*);
SOAP_FMAC3 _ns5__SrbUpload * SOAP_FMAC4 soap_instantiate__ns5__SrbUpload(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns5__SrbUpload(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns5__myData
#define SOAP_TYPE_ns5__myData (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__myData(struct soap*, const char*, int, const ns5__myData *, const char*);
SOAP_FMAC3 ns5__myData * SOAP_FMAC4 soap_get_ns5__myData(struct soap*, ns5__myData *, const char*, const char*);
SOAP_FMAC3 ns5__myData * SOAP_FMAC4 soap_in_ns5__myData(struct soap*, const char*, ns5__myData *, const char*);
SOAP_FMAC5 ns5__myData * SOAP_FMAC6 soap_new_ns5__myData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns5__myData(struct soap*, ns5__myData*);
SOAP_FMAC3 ns5__myData * SOAP_FMAC4 soap_instantiate_ns5__myData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns5__myData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns5__SrbAuth
#define SOAP_TYPE_ns5__SrbAuth (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns5__SrbAuth(struct soap*, const char*, int, const ns5__SrbAuth *, const char*);
SOAP_FMAC3 ns5__SrbAuth * SOAP_FMAC4 soap_get_ns5__SrbAuth(struct soap*, ns5__SrbAuth *, const char*, const char*);
SOAP_FMAC3 ns5__SrbAuth * SOAP_FMAC4 soap_in_ns5__SrbAuth(struct soap*, const char*, ns5__SrbAuth *, const char*);
SOAP_FMAC5 ns5__SrbAuth * SOAP_FMAC6 soap_new_ns5__SrbAuth(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns5__SrbAuth(struct soap*, ns5__SrbAuth*);
SOAP_FMAC3 ns5__SrbAuth * SOAP_FMAC4 soap_instantiate_ns5__SrbAuth(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns5__SrbAuth(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns4__hexBinary
#define SOAP_TYPE_ns4__hexBinary (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__hexBinary(struct soap*, const char*, int, const ns4__hexBinary *, const char*);
SOAP_FMAC3 ns4__hexBinary * SOAP_FMAC4 soap_get_ns4__hexBinary(struct soap*, ns4__hexBinary *, const char*, const char*);
SOAP_FMAC3 ns4__hexBinary * SOAP_FMAC4 soap_in_ns4__hexBinary(struct soap*, const char*, ns4__hexBinary *, const char*);
SOAP_FMAC5 ns4__hexBinary * SOAP_FMAC6 soap_new_ns4__hexBinary(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns4__hexBinary(struct soap*, ns4__hexBinary*);
SOAP_FMAC3 ns4__hexBinary * SOAP_FMAC4 soap_instantiate_ns4__hexBinary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns4__hexBinary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns4__base64Binary
#define SOAP_TYPE_ns4__base64Binary (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns4__base64Binary(struct soap*, const char*, int, const ns4__base64Binary *, const char*);
SOAP_FMAC3 ns4__base64Binary * SOAP_FMAC4 soap_get_ns4__base64Binary(struct soap*, ns4__base64Binary *, const char*, const char*);
SOAP_FMAC3 ns4__base64Binary * SOAP_FMAC4 soap_in_ns4__base64Binary(struct soap*, const char*, ns4__base64Binary *, const char*);
SOAP_FMAC5 ns4__base64Binary * SOAP_FMAC6 soap_new_ns4__base64Binary(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns4__base64Binary(struct soap*, ns4__base64Binary*);
SOAP_FMAC3 ns4__base64Binary * SOAP_FMAC4 soap_instantiate_ns4__base64Binary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns4__base64Binary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__Include
#define SOAP_TYPE_ns3__Include (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__Include(struct soap*, const char*, int, const ns3__Include *, const char*);
SOAP_FMAC3 ns3__Include * SOAP_FMAC4 soap_get_ns3__Include(struct soap*, ns3__Include *, const char*, const char*);
SOAP_FMAC3 ns3__Include * SOAP_FMAC4 soap_in_ns3__Include(struct soap*, const char*, ns3__Include *, const char*);
SOAP_FMAC5 ns3__Include * SOAP_FMAC6 soap_new_ns3__Include(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns3__Include(struct soap*, ns3__Include*);
SOAP_FMAC3 ns3__Include * SOAP_FMAC4 soap_instantiate_ns3__Include(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__Include(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__myData
#define SOAP_TYPE__ns2__myData (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__myData(struct soap*, const char*, int, const _ns2__myData *, const char*);
SOAP_FMAC3 _ns2__myData * SOAP_FMAC4 soap_get__ns2__myData(struct soap*, _ns2__myData *, const char*, const char*);
SOAP_FMAC3 _ns2__myData * SOAP_FMAC4 soap_in__ns2__myData(struct soap*, const char*, _ns2__myData *, const char*);
SOAP_FMAC5 _ns2__myData * SOAP_FMAC6 soap_new__ns2__myData(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns2__myData(struct soap*, _ns2__myData*);
SOAP_FMAC3 _ns2__myData * SOAP_FMAC4 soap_instantiate__ns2__myData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__myData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns2__SrbDownload
#define SOAP_TYPE__ns2__SrbDownload (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns2__SrbDownload(struct soap*, const char*, int, const _ns2__SrbDownload *, const char*);
SOAP_FMAC3 _ns2__SrbDownload * SOAP_FMAC4 soap_get__ns2__SrbDownload(struct soap*, _ns2__SrbDownload *, const char*, const char*);
SOAP_FMAC3 _ns2__SrbDownload * SOAP_FMAC4 soap_in__ns2__SrbDownload(struct soap*, const char*, _ns2__SrbDownload *, const char*);
SOAP_FMAC5 _ns2__SrbDownload * SOAP_FMAC6 soap_new__ns2__SrbDownload(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns2__SrbDownload(struct soap*, _ns2__SrbDownload*);
SOAP_FMAC3 _ns2__SrbDownload * SOAP_FMAC4 soap_instantiate__ns2__SrbDownload(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns2__SrbDownload(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns2__SrbAuth
#define SOAP_TYPE_ns2__SrbAuth (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__SrbAuth(struct soap*, const char*, int, const ns2__SrbAuth *, const char*);
SOAP_FMAC3 ns2__SrbAuth * SOAP_FMAC4 soap_get_ns2__SrbAuth(struct soap*, ns2__SrbAuth *, const char*, const char*);
SOAP_FMAC3 ns2__SrbAuth * SOAP_FMAC4 soap_in_ns2__SrbAuth(struct soap*, const char*, ns2__SrbAuth *, const char*);
SOAP_FMAC5 ns2__SrbAuth * SOAP_FMAC6 soap_new_ns2__SrbAuth(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns2__SrbAuth(struct soap*, ns2__SrbAuth*);
SOAP_FMAC3 ns2__SrbAuth * SOAP_FMAC4 soap_instantiate_ns2__SrbAuth(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns2__SrbAuth(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SrbListResponse
#define SOAP_TYPE__ns1__SrbListResponse (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SrbListResponse(struct soap*, const char*, int, const _ns1__SrbListResponse *, const char*);
SOAP_FMAC3 _ns1__SrbListResponse * SOAP_FMAC4 soap_get__ns1__SrbListResponse(struct soap*, _ns1__SrbListResponse *, const char*, const char*);
SOAP_FMAC3 _ns1__SrbListResponse * SOAP_FMAC4 soap_in__ns1__SrbListResponse(struct soap*, const char*, _ns1__SrbListResponse *, const char*);
SOAP_FMAC5 _ns1__SrbListResponse * SOAP_FMAC6 soap_new__ns1__SrbListResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SrbListResponse(struct soap*, _ns1__SrbListResponse*);
SOAP_FMAC3 _ns1__SrbListResponse * SOAP_FMAC4 soap_instantiate__ns1__SrbListResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SrbListResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__SrbList
#define SOAP_TYPE__ns1__SrbList (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__SrbList(struct soap*, const char*, int, const _ns1__SrbList *, const char*);
SOAP_FMAC3 _ns1__SrbList * SOAP_FMAC4 soap_get__ns1__SrbList(struct soap*, _ns1__SrbList *, const char*, const char*);
SOAP_FMAC3 _ns1__SrbList * SOAP_FMAC4 soap_in__ns1__SrbList(struct soap*, const char*, _ns1__SrbList *, const char*);
SOAP_FMAC5 _ns1__SrbList * SOAP_FMAC6 soap_new__ns1__SrbList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__ns1__SrbList(struct soap*, _ns1__SrbList*);
SOAP_FMAC3 _ns1__SrbList * SOAP_FMAC4 soap_instantiate__ns1__SrbList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__SrbList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__SrbAuth
#define SOAP_TYPE_ns1__SrbAuth (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SrbAuth(struct soap*, const char*, int, const ns1__SrbAuth *, const char*);
SOAP_FMAC3 ns1__SrbAuth * SOAP_FMAC4 soap_get_ns1__SrbAuth(struct soap*, ns1__SrbAuth *, const char*, const char*);
SOAP_FMAC3 ns1__SrbAuth * SOAP_FMAC4 soap_in_ns1__SrbAuth(struct soap*, const char*, ns1__SrbAuth *, const char*);
SOAP_FMAC5 ns1__SrbAuth * SOAP_FMAC6 soap_new_ns1__SrbAuth(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns1__SrbAuth(struct soap*, ns1__SrbAuth*);
SOAP_FMAC3 ns1__SrbAuth * SOAP_FMAC4 soap_instantiate_ns1__SrbAuth(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__SrbAuth(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__hexBinary
#define SOAP_TYPE_xsd__hexBinary (13)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__hexBinary(struct soap*, const char*, int, const xsd__hexBinary *, const char*);
SOAP_FMAC3 xsd__hexBinary * SOAP_FMAC4 soap_get_xsd__hexBinary(struct soap*, xsd__hexBinary *, const char*, const char*);
SOAP_FMAC3 xsd__hexBinary * SOAP_FMAC4 soap_in_xsd__hexBinary(struct soap*, const char*, xsd__hexBinary *, const char*);
SOAP_FMAC5 xsd__hexBinary * SOAP_FMAC6 soap_new_xsd__hexBinary(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__hexBinary(struct soap*, xsd__hexBinary*);
SOAP_FMAC3 xsd__hexBinary * SOAP_FMAC4 soap_instantiate_xsd__hexBinary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__hexBinary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (7)
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const xsd__base64Binary *, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, xsd__base64Binary *, const char*);
SOAP_FMAC5 xsd__base64Binary * SOAP_FMAC6 soap_new_xsd__base64Binary(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__base64Binary(struct soap*, xsd__base64Binary*);
SOAP_FMAC3 xsd__base64Binary * SOAP_FMAC4 soap_instantiate_xsd__base64Binary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__base64Binary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns8__SrbUpload
#define SOAP_TYPE___ns8__SrbUpload (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns8__SrbUpload(struct soap*, const struct __ns8__SrbUpload *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns8__SrbUpload(struct soap*, struct __ns8__SrbUpload *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns8__SrbUpload(struct soap*, const struct __ns8__SrbUpload *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns8__SrbUpload(struct soap*, const char*, int, const struct __ns8__SrbUpload *, const char*);
SOAP_FMAC3 struct __ns8__SrbUpload * SOAP_FMAC4 soap_get___ns8__SrbUpload(struct soap*, struct __ns8__SrbUpload *, const char*, const char*);
SOAP_FMAC3 struct __ns8__SrbUpload * SOAP_FMAC4 soap_in___ns8__SrbUpload(struct soap*, const char*, struct __ns8__SrbUpload *, const char*);
SOAP_FMAC5 struct __ns8__SrbUpload * SOAP_FMAC6 soap_new___ns8__SrbUpload(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns8__SrbUpload(struct soap*, struct __ns8__SrbUpload*);
SOAP_FMAC3 struct __ns8__SrbUpload * SOAP_FMAC4 soap_instantiate___ns8__SrbUpload(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns8__SrbUpload(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns8__SrbUploadResponse
#define SOAP_TYPE___ns8__SrbUploadResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns8__SrbUploadResponse(struct soap*, const struct __ns8__SrbUploadResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns8__SrbUploadResponse(struct soap*, struct __ns8__SrbUploadResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns8__SrbUploadResponse(struct soap*, const struct __ns8__SrbUploadResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns8__SrbUploadResponse(struct soap*, const char*, int, const struct __ns8__SrbUploadResponse *, const char*);
SOAP_FMAC3 struct __ns8__SrbUploadResponse * SOAP_FMAC4 soap_get___ns8__SrbUploadResponse(struct soap*, struct __ns8__SrbUploadResponse *, const char*, const char*);
SOAP_FMAC3 struct __ns8__SrbUploadResponse * SOAP_FMAC4 soap_in___ns8__SrbUploadResponse(struct soap*, const char*, struct __ns8__SrbUploadResponse *, const char*);
SOAP_FMAC5 struct __ns8__SrbUploadResponse * SOAP_FMAC6 soap_new___ns8__SrbUploadResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns8__SrbUploadResponse(struct soap*, struct __ns8__SrbUploadResponse*);
SOAP_FMAC3 struct __ns8__SrbUploadResponse * SOAP_FMAC4 soap_instantiate___ns8__SrbUploadResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns8__SrbUploadResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns7__SrbDownload
#define SOAP_TYPE___ns7__SrbDownload (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns7__SrbDownload(struct soap*, const struct __ns7__SrbDownload *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns7__SrbDownload(struct soap*, struct __ns7__SrbDownload *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns7__SrbDownload(struct soap*, const struct __ns7__SrbDownload *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns7__SrbDownload(struct soap*, const char*, int, const struct __ns7__SrbDownload *, const char*);
SOAP_FMAC3 struct __ns7__SrbDownload * SOAP_FMAC4 soap_get___ns7__SrbDownload(struct soap*, struct __ns7__SrbDownload *, const char*, const char*);
SOAP_FMAC3 struct __ns7__SrbDownload * SOAP_FMAC4 soap_in___ns7__SrbDownload(struct soap*, const char*, struct __ns7__SrbDownload *, const char*);
SOAP_FMAC5 struct __ns7__SrbDownload * SOAP_FMAC6 soap_new___ns7__SrbDownload(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns7__SrbDownload(struct soap*, struct __ns7__SrbDownload*);
SOAP_FMAC3 struct __ns7__SrbDownload * SOAP_FMAC4 soap_instantiate___ns7__SrbDownload(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns7__SrbDownload(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns7__SrbDownloadResponse
#define SOAP_TYPE___ns7__SrbDownloadResponse (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns7__SrbDownloadResponse(struct soap*, const struct __ns7__SrbDownloadResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns7__SrbDownloadResponse(struct soap*, struct __ns7__SrbDownloadResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns7__SrbDownloadResponse(struct soap*, const struct __ns7__SrbDownloadResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns7__SrbDownloadResponse(struct soap*, const char*, int, const struct __ns7__SrbDownloadResponse *, const char*);
SOAP_FMAC3 struct __ns7__SrbDownloadResponse * SOAP_FMAC4 soap_get___ns7__SrbDownloadResponse(struct soap*, struct __ns7__SrbDownloadResponse *, const char*, const char*);
SOAP_FMAC3 struct __ns7__SrbDownloadResponse * SOAP_FMAC4 soap_in___ns7__SrbDownloadResponse(struct soap*, const char*, struct __ns7__SrbDownloadResponse *, const char*);
SOAP_FMAC5 struct __ns7__SrbDownloadResponse * SOAP_FMAC6 soap_new___ns7__SrbDownloadResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns7__SrbDownloadResponse(struct soap*, struct __ns7__SrbDownloadResponse*);
SOAP_FMAC3 struct __ns7__SrbDownloadResponse * SOAP_FMAC4 soap_instantiate___ns7__SrbDownloadResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns7__SrbDownloadResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns6__SrbList
#define SOAP_TYPE___ns6__SrbList (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns6__SrbList(struct soap*, const struct __ns6__SrbList *);
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns6__SrbList(struct soap*, struct __ns6__SrbList *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns6__SrbList(struct soap*, const struct __ns6__SrbList *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns6__SrbList(struct soap*, const char*, int, const struct __ns6__SrbList *, const char*);
SOAP_FMAC3 struct __ns6__SrbList * SOAP_FMAC4 soap_get___ns6__SrbList(struct soap*, struct __ns6__SrbList *, const char*, const char*);
SOAP_FMAC3 struct __ns6__SrbList * SOAP_FMAC4 soap_in___ns6__SrbList(struct soap*, const char*, struct __ns6__SrbList *, const char*);
SOAP_FMAC5 struct __ns6__SrbList * SOAP_FMAC6 soap_new___ns6__SrbList(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___ns6__SrbList(struct soap*, struct __ns6__SrbList*);
SOAP_FMAC3 struct __ns6__SrbList * SOAP_FMAC4 soap_instantiate___ns6__SrbList(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns6__SrbList(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns5__SrbUpload
#define SOAP_TYPE_PointerTo_ns5__SrbUpload (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns5__SrbUpload(struct soap*, _ns5__SrbUpload *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns5__SrbUpload(struct soap*, _ns5__SrbUpload *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns5__SrbUpload(struct soap*, const char *, int, _ns5__SrbUpload *const*, const char *);
SOAP_FMAC3 _ns5__SrbUpload ** SOAP_FMAC4 soap_get_PointerTo_ns5__SrbUpload(struct soap*, _ns5__SrbUpload **, const char*, const char*);
SOAP_FMAC3 _ns5__SrbUpload ** SOAP_FMAC4 soap_in_PointerTo_ns5__SrbUpload(struct soap*, const char*, _ns5__SrbUpload **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns5__fileInfo
#define SOAP_TYPE_PointerTo_ns5__fileInfo (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns5__fileInfo(struct soap*, _ns5__fileInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns5__fileInfo(struct soap*, _ns5__fileInfo *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns5__fileInfo(struct soap*, const char *, int, _ns5__fileInfo *const*, const char *);
SOAP_FMAC3 _ns5__fileInfo ** SOAP_FMAC4 soap_get_PointerTo_ns5__fileInfo(struct soap*, _ns5__fileInfo **, const char*, const char*);
SOAP_FMAC3 _ns5__fileInfo ** SOAP_FMAC4 soap_in_PointerTo_ns5__fileInfo(struct soap*, const char*, _ns5__fileInfo **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__SrbDownload
#define SOAP_TYPE_PointerTo_ns2__SrbDownload (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__SrbDownload(struct soap*, _ns2__SrbDownload *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__SrbDownload(struct soap*, _ns2__SrbDownload *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__SrbDownload(struct soap*, const char *, int, _ns2__SrbDownload *const*, const char *);
SOAP_FMAC3 _ns2__SrbDownload ** SOAP_FMAC4 soap_get_PointerTo_ns2__SrbDownload(struct soap*, _ns2__SrbDownload **, const char*, const char*);
SOAP_FMAC3 _ns2__SrbDownload ** SOAP_FMAC4 soap_in_PointerTo_ns2__SrbDownload(struct soap*, const char*, _ns2__SrbDownload **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns2__myData
#define SOAP_TYPE_PointerTo_ns2__myData (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns2__myData(struct soap*, _ns2__myData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns2__myData(struct soap*, _ns2__myData *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns2__myData(struct soap*, const char *, int, _ns2__myData *const*, const char *);
SOAP_FMAC3 _ns2__myData ** SOAP_FMAC4 soap_get_PointerTo_ns2__myData(struct soap*, _ns2__myData **, const char*, const char*);
SOAP_FMAC3 _ns2__myData ** SOAP_FMAC4 soap_in_PointerTo_ns2__myData(struct soap*, const char*, _ns2__myData **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SrbListResponse
#define SOAP_TYPE_PointerTo_ns1__SrbListResponse (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SrbListResponse(struct soap*, _ns1__SrbListResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SrbListResponse(struct soap*, _ns1__SrbListResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SrbListResponse(struct soap*, const char *, int, _ns1__SrbListResponse *const*, const char *);
SOAP_FMAC3 _ns1__SrbListResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__SrbListResponse(struct soap*, _ns1__SrbListResponse **, const char*, const char*);
SOAP_FMAC3 _ns1__SrbListResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__SrbListResponse(struct soap*, const char*, _ns1__SrbListResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__SrbList
#define SOAP_TYPE_PointerTo_ns1__SrbList (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__SrbList(struct soap*, _ns1__SrbList *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__SrbList(struct soap*, _ns1__SrbList *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__SrbList(struct soap*, const char *, int, _ns1__SrbList *const*, const char *);
SOAP_FMAC3 _ns1__SrbList ** SOAP_FMAC4 soap_get_PointerTo_ns1__SrbList(struct soap*, _ns1__SrbList **, const char*, const char*);
SOAP_FMAC3 _ns1__SrbList ** SOAP_FMAC4 soap_in_PointerTo_ns1__SrbList(struct soap*, const char*, _ns1__SrbList **, const char*);

#ifndef SOAP_TYPE_PointerTons5__myData
#define SOAP_TYPE_PointerTons5__myData (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons5__myData(struct soap*, ns5__myData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons5__myData(struct soap*, ns5__myData *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons5__myData(struct soap*, const char *, int, ns5__myData *const*, const char *);
SOAP_FMAC3 ns5__myData ** SOAP_FMAC4 soap_get_PointerTons5__myData(struct soap*, ns5__myData **, const char*, const char*);
SOAP_FMAC3 ns5__myData ** SOAP_FMAC4 soap_in_PointerTons5__myData(struct soap*, const char*, ns5__myData **, const char*);

#ifndef SOAP_TYPE_PointerTons5__SrbAuth
#define SOAP_TYPE_PointerTons5__SrbAuth (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons5__SrbAuth(struct soap*, ns5__SrbAuth *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons5__SrbAuth(struct soap*, ns5__SrbAuth *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons5__SrbAuth(struct soap*, const char *, int, ns5__SrbAuth *const*, const char *);
SOAP_FMAC3 ns5__SrbAuth ** SOAP_FMAC4 soap_get_PointerTons5__SrbAuth(struct soap*, ns5__SrbAuth **, const char*, const char*);
SOAP_FMAC3 ns5__SrbAuth ** SOAP_FMAC4 soap_in_PointerTons5__SrbAuth(struct soap*, const char*, ns5__SrbAuth **, const char*);

#ifndef SOAP_TYPE_PointerTons3__Include
#define SOAP_TYPE_PointerTons3__Include (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__Include(struct soap*, ns3__Include *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__Include(struct soap*, ns3__Include *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__Include(struct soap*, const char *, int, ns3__Include *const*, const char *);
SOAP_FMAC3 ns3__Include ** SOAP_FMAC4 soap_get_PointerTons3__Include(struct soap*, ns3__Include **, const char*, const char*);
SOAP_FMAC3 ns3__Include ** SOAP_FMAC4 soap_in_PointerTons3__Include(struct soap*, const char*, ns3__Include **, const char*);

#ifndef SOAP_TYPE_PointerTons2__SrbAuth
#define SOAP_TYPE_PointerTons2__SrbAuth (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__SrbAuth(struct soap*, ns2__SrbAuth *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__SrbAuth(struct soap*, ns2__SrbAuth *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__SrbAuth(struct soap*, const char *, int, ns2__SrbAuth *const*, const char *);
SOAP_FMAC3 ns2__SrbAuth ** SOAP_FMAC4 soap_get_PointerTons2__SrbAuth(struct soap*, ns2__SrbAuth **, const char*, const char*);
SOAP_FMAC3 ns2__SrbAuth ** SOAP_FMAC4 soap_in_PointerTons2__SrbAuth(struct soap*, const char*, ns2__SrbAuth **, const char*);

#ifndef SOAP_TYPE_PointerTons1__SrbAuth
#define SOAP_TYPE_PointerTons1__SrbAuth (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__SrbAuth(struct soap*, ns1__SrbAuth *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__SrbAuth(struct soap*, ns1__SrbAuth *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__SrbAuth(struct soap*, const char *, int, ns1__SrbAuth *const*, const char *);
SOAP_FMAC3 ns1__SrbAuth ** SOAP_FMAC4 soap_get_PointerTons1__SrbAuth(struct soap*, ns1__SrbAuth **, const char*, const char*);
SOAP_FMAC3 ns1__SrbAuth ** SOAP_FMAC4 soap_in_PointerTons1__SrbAuth(struct soap*, const char*, ns1__SrbAuth **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (6)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of soapH.h */
