/*=========================================================================

 Program: ALBA (Agile Library for Biomedical Applications)
 Module: albaInteractorExtractIsosurfaceTest
 Authors: Stefano Perticoni
 
 Copyright (c) BIC
 All rights reserved. See Copyright.txt or


 This software is distributed WITHOUT ANY WARRANTY; without even
 the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

#ifndef __CPP_UNIT_albaInteractorExtractIsosurfaceTest_H__
#define __CPP_UNIT_albaInteractorExtractIsosurfaceTest_H__

#include "albaTest.h"

class albaInteractorExtractIsosurfaceTest : public albaTest
{
  public:

    CPPUNIT_TEST_SUITE( albaInteractorExtractIsosurfaceTest );
    CPPUNIT_TEST(TestFixture);
    CPPUNIT_TEST(TestConstructor);
    CPPUNIT_TEST(TestStartInteraction);
    CPPUNIT_TEST(TestOnMouseMove);
    CPPUNIT_TEST(TestOnLeftButtonDown);
    CPPUNIT_TEST(TestOnButtonUp);
    CPPUNIT_TEST_SUITE_END();

  protected:

    void TestFixture();
    void TestConstructor();
    void TestStartInteraction();

    /** 
    1 line of leaks generated by albaLogMessage (only) in albaInteractorExtractIsosurface::OnMouseMove()*/
    void TestOnMouseMove();

    void TestOnLeftButtonDown();
    void TestOnButtonUp();
      
};

#endif
