/*=========================================================================

 Program: MAF2
 Module: mafInteractorExtractIsosurfaceTest
 Authors: Stefano Perticoni
 
 Copyright (c) B3C
 All rights reserved. See Copyright.txt or
 http://www.scsitaly.com/Copyright.htm for details.

 This software is distributed WITHOUT ANY WARRANTY; without even
 the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

#ifndef __CPP_UNIT_mafInteractorExtractIsosurfaceTest_H__
#define __CPP_UNIT_mafInteractorExtractIsosurfaceTest_H__

#include "mafTest.h"

class mafInteractorExtractIsosurfaceTest : public mafTest
{
  public:

    CPPUNIT_TEST_SUITE( mafInteractorExtractIsosurfaceTest );
    CPPUNIT_TEST(TestFixture);
    CPPUNIT_TEST(TestConstructor);
    CPPUNIT_TEST(TestStartInteraction);
    CPPUNIT_TEST(TestOnMouseMove);
    CPPUNIT_TEST(TestOnLeftButtonDown);
    CPPUNIT_TEST(TestOnButtonUp);
    CPPUNIT_TEST_SUITE_END();

  protected:

    void TestFixture();
    void TestConstructor();
    void TestStartInteraction();

    /** 
    1 line of leaks generated by mafLogMessage (only) in mafInteractorExtractIsosurface::OnMouseMove()*/
    void TestOnMouseMove();

    void TestOnLeftButtonDown();
    void TestOnButtonUp();
      
};

#endif
