REM -----------------------------------------------------------------------------
REM cmake execution driver script
REM -----------------------------------------------------------------------------

IF "%1" == "MED_QA" GOTO MED_QA
IF "%1" == "MAF_MED_DEBUG_DLL_TEST" GOTO MAF_MED_DEBUG_DLL_TEST
IF "%1" == "MAFMED_DEBUG" GOTO MAFMED_DEBUG
IF "%1" == "MAFMED_DEBUG_2010" GOTO MAFMED_DEBUG_2010
IF "%1" == "MAFMED_DOCUMENTATION" GOTO MAFMED_DOCUMENTATION
IF "%1" == "VAPP_DEBUG" GOTO VAPP_DEBUG
IF "%1" == "VAPP_RELEASE" GOTO VAPP_RELEASE
IF "%1" == "VAPP_MEDICAL_RELEASE" GOTO VAPP_MEDICAL_RELEASE
IF "%1" == "VAPP_RELEASE_2005" GOTO VAPP_RELEASE_2005
IF "%1" == "VAPP_RELEASE_2008" GOTO VAPP_RELEASE_2008
IF "%1" == "VAPP_RELEASE_2010" GOTO VAPP_RELEASE_2010
IF NOT "%1" == "MAF_DEBUG" GOTO UNKNOWN_CONDITION

:MED_QA

mkdir Medical_Parabuild.build
cd Medical_Parabuild.build

cmake.exe  ../Medical_Parabuild  ^
  -G"Visual Studio 10" ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DDART_TESTING_TIMEOUT:STRING=120 ^
  -DMED_QA:BOOL=ON ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0_VS2010_BUILD/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0_VS2010_BUILD/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/openMAF_ITK_Medical_Parabuild/openMAF_ITK_Parabuild.build" 
  
cd ..

GOTO END

:MAF_MED_DEBUG_DLL_TEST

cd Medical_Parabuild

cmake.exe  .  ^
  -G"Visual Studio 7 .NET 2003" ^
  -DMED_BUILD_MEDDLL:BOOL=ON ^
  -DBUILD_TESTING:BOOL=ON ^
  -DDART_TESTING_TIMEOUT:STRING=120 ^
  -DBUILD_EXAMPLES:BOOL=ON ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/openMAF_ITK_Medical_Parabuild/openMAF_ITK_Parabuild" 
  
cd ..

GOTO END

:MAFMED_DEBUG

cd Medical_Parabuild

cmake.exe  .  ^
  -G"Visual Studio 7 .NET 2003" ^
  -DBUILD_TESTING:BOOL=ON ^
  -DDART_TESTING_TIMEOUT:STRING=120 ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DBUILD_IPOSE:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/openMAF_ITK_Medical_Parabuild/openMAF_ITK_Parabuild" 

cd ..   

GOTO END

:MAFMED_DEBUG_2010

cd Medical_Parabuild

cmake.exe  .  ^
  -G"Visual Studio 10" ^
  -DBUILD_TESTING:BOOL=ON ^
  -DDART_TESTING_TIMEOUT:STRING=120 ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DBUILD_IPOSE:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0_VS2010_BUILD/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0_VS2010_BUILD/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/openMAF_ITK_Medical_Parabuild/openMAF_ITK_Parabuild" 

cd ..   

GOTO END



:MAFMED_DOCUMENTATION

cd Medical_Parabuild

cmake.exe  .  ^
  -G"Visual Studio 7 .NET 2003" ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/openMAF_ITK_Medical_Parabuild/openMAF_ITK_Parabuild" ^
  -DBUILD_DOCUMENTATION=ON

cd ..   

GOTO END

:VAPP_DEBUG

cd Medical_Parabuild

cmake.exe . ^
  -G"Visual Studio 7 .NET 2003" ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DBUILD_IPOSE:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/vapp/openMAF_ITK_Parabuild" 

  
cd ..   
   
GOTO END

:VAPP_RELEASE

cd Medical_Parabuild

cmake.exe     ^
  -G"Visual Studio 7 .NET 2003" ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DBUILD_IPOSE:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/vapp/openMAF_ITK_Parabuild" 
  
cd ..   

GOTO END

:VAPP_MEDICAL_RELEASE

cd Medical_Parabuild

cmake.exe     ^
  -G"Visual Studio 7 .NET 2003" ^
  -DBUILD_EXAMPLES:BOOL=ON ^
  -DBUILD_IPOSE:BOOL=ON ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/vapp/openMAF_ITK_Parabuild" ^
  -DIPOSE_EXECUTABLE_OUTPUT_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/vapp/Medical_Parabuild/bin/Release" ^
  -DIPOSE_INSTALLER_EXECUTABLE_OUTPUT_DIR:PATH="%PARABUILD_CHECKOUT_DIR%/vapp/Medical_Parabuild/bin/Deploy"
  
cd ..   

GOTO END

:VAPP_RELEASE_2005

cd Medical_Parabuild

cmake.exe     ^
  -G"Visual Studio 8 2005" ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DBUILD_IPOSE:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/vapp/openMAF_ITK_Parabuild" 
  
cd ..   

GOTO END


:VAPP_RELEASE_2008

cd Medical_Parabuild

cmake.exe     ^
  -G"Visual Studio 9 2008" ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DBUILD_IPOSE:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/vapp/openMAF_ITK_Parabuild" 
  
cd ..   

GOTO END

:VAPP_RELEASE_2010

cd Medical_Parabuild

cmake.exe     ^
  -G"Visual Studio 10" ^
  -DBUILD_EXAMPLES:BOOL=OFF ^
  -DBUILD_TESTING:BOOL=OFF ^
  -DBUILD_IPOSE:BOOL=OFF ^
  -DCMAKE_BACKWARDS_COMPATIBILITY:STRING=2.0 ^
  -DCPPUNIT_INCLUDE_DIR:PATH="C:/cppunit-1.12.0_VS2010_BUILD/cppunit-1.12.0/include" ^
  -DCPPUNIT_LIBRARY:FILEPATH="C:/cppunit-1.12.0_VS2010_BUILD/cppunit-1.12.0/lib/cppunitd.lib" ^
  -DMAF_BINARY_PATH:PATH="%PARABUILD_CHECKOUT_DIR%/vapp/openMAF_ITK_Parabuild" 
  
cd ..   

GOTO END

:UNKNOWN_CONDITION

:END
