/*=========================================================================

 Program: ALBA (Agile Library for Biomedical Applications)
 Module: albaGUITree
 Authors: Silvano Imboden
 
 Copyright (c) BIC
 All rights reserved. See Copyright.txt or


 This software is distributed WITHOUT ANY WARRANTY; without even
 the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 PURPOSE.  See the above copyright notice for more information.

=========================================================================*/
#ifndef __albaGUITree_H__
#define __albaGUITree_H__
//----------------------------------------------------------------------------
// Include:
//----------------------------------------------------------------------------
#include <wx/laywin.h>
#include <wx/image.h>
#include <wx/imaglist.h>
#include <wx/treectrl.h>
#include <wx/hash.h>
#include "albaEvent.h"
#include "albaObserver.h"
#include "albaGUINamedPanel.h"
#include "albaServiceClient.h"
#include "albaAbsLogicManager.h"

//----------------------------------------------------------------------------
// const :
//----------------------------------------------------------------------------
const int ID_TREE = 200;
//----------------------------------------------------------------------------
// albaGUITree :
//----------------------------------------------------------------------------
/**
albaGUITree allows a simplified and lot easier use of a wxWindows tree widget. 
- Nodes have id, parent, label and icon.
- Nodes can be added and deleted
- Parent,label and icon can be changed.
- Delete or reparent a node affect its whole subtree.
- albaGUITree doesn't assume anything about what the nodes represented, thus nodes objects may be everything. 
  Nodes are referenced by a node_id of type long long, so a node_id may be a numeric value or a pointer.
- albaGUITree doesn't use the wxWindows event-system: to receive event notification provide 
  a albaObserver object by calling SetListener.

  events generated by albaGUITree:
- VME_SELECTED   node_id

\par implementation details:
the term "Node" refer to the object represented in the Tree,
the term "Item" refer to the graphics object shown in the Tree.

Calling wxTreeCtrl::AddNode return an object of type wxTreeCtrlItem,
these objects are to be kept somewhere to be able to edit or delete the items later.
The easy solution is to store a pointer to wxTreeCtrlItem in the node,
but this will mean that albaGUITree has some knowledge on the node objects 
thus making albaGUITree non-general-purposes and also that
every node can be connected to one albaGUITree only.

The solution adopted here is to store all the wxTreeCtrlItem in a HashTable (m_NodeTable)
indexed by the node_id's. Thus explicit conversion between node_ids and items has to be addressed.

ItemFromNode is implemented using m_NodeTable. Note that wxHashTable store only object 
of type albaGUITreeTableElement so a new class albaGUITreeTableItem was derived from wxHashTableItem
to store a pointer to wxTreeCtrlItem

NodeFromItem may be implemented searching all the elements in m_NodeTable but this
will be time-consuming, another solution is to store the node_id in the item.
Items may store user-data in a class derived from wxTreeItemData, so a class albaGUITreeItemData
was created for this purposes. A new albaGUITreeItemData object is created every time 
an item is inserted in the tree.

Further aspect:
One Item may have a cross-icon that mean that it has children and thus can be opened,
to show the cross-icon the developer must call SetItemHasChildren.
wxTreeCtrl doesn't set-up the HasChildren flag itself, so when a node is added or deleted the 
HasChildren flag of the parent has to be kept consistent.Another flag control if 
a subtree is expanded or collapsed, this flag has to be kept consistent when moving a node.
  
Moving a node:
wxTreeCtrl doesn't provide a way to change item's parent, so that operation has to be implemented
explicitly. Delete and recreate the item doesn't work because delete the item destroy
all the items in the subtree.The correct approach is to copy the item under the new parent,
recursively move all the item in the subtree, and then delete the old item.During this operation 
the HasChildren flag, the IsExpanded flag and the HashTable contents has to be kept consistent.

Deleting a node:
Deleting an item destroy all the sub-items,leaving the m_NodeTable inconsistent.
To correctly implement the operation, DeleteNode must call itself recursively on the 
item subtree, then Delete the item and remove the corresponding m_NodeTable entry. 
*/

//----------------------------------------------------------------------------
// albaGUITreeItemData :
/// Data to be attached to an item of albaGUITree, holds the reference to a node_id 
//----------------------------------------------------------------------------
class albaGUITreeItemData : public wxTreeItemData {
public:
	albaGUITreeItemData(long long node_id, bool expanded) { m_NodeId = node_id; m_Expanded = expanded; };

	/** Returns NodeId*/
	long long GetNode() { return m_NodeId; };

	/** Returns Expanded virtual node state, when a node has no child it result not expanded in any case,
	but we need a status information also for those nodes*/
	bool GetExpanded() const { return m_Expanded; }

	/** Sets Expanded virtual node state, , when a node has no child it result not expanded in any case,
	but we need a status information also for those nodes */
	void SetExpanded(bool expanded) { m_Expanded = expanded; }

protected:
	long long m_NodeId;
	bool m_Expanded;
};


class albaTreeCtrl : public wxTreeCtrl
{
public: 
	albaTreeCtrl(wxWindow *parent, wxWindowID id = wxID_ANY,
		const wxPoint& pos = wxDefaultPosition,
		const wxSize& size = wxDefaultSize,
		long style = wxTR_HAS_BUTTONS | wxTR_LINES_AT_ROOT,
		const wxValidator& validator = wxDefaultValidator,
		const wxString& name = wxASCII_STR(wxTreeCtrlNameStr));

	virtual bool IsExpanded(const wxTreeItemId& item);

	virtual bool MSWOnNotify(int idCtrl, WXLPARAM lParam, WXLPARAM *result);

	wxTreeItemId AppendItem(const wxTreeItemId& parent, const wxString& text, int image = -1, int selImage = -1, wxTreeItemData *data = NULL);

	virtual void Expand(const wxTreeItemId& item);
	virtual void Collapse(const wxTreeItemId& item);
	virtual void CollapseAndReset(const wxTreeItemId& item);
	virtual void Toggle(const wxTreeItemId& item);
};


class ALBA_EXPORT albaGUITree: public albaGUINamedPanel, public albaServiceClient
{
public:
                 albaGUITree (wxWindow* parent, wxWindowID id=-1, bool CloseButton = false, bool HideTitle = false); 
  virtual       ~albaGUITree();

  /** Clears all items in the tree. */
	void Reset();
  
	/** Create a new tree item with the specified parent,label and icon. 
      Set parent = 0 to create the root. 0 is not a valid node_id.
  */
	bool AddNode(long long node_id, long long parent_id , wxString label, bool expanded, int icon = 0);
  
	/** Delete the specified node, and its subtree. */
	bool DeleteNode(long long node_id);
  
	/** Set the label for the node. */
	bool SetNodeLabel(long long node_id, wxString label);

  /** Get the label for the node. Add by Mucci 19/09/2007*/
  wxString GetNodeLabel(long long node_id);

  /** Check if the node has children. Add by Mucci 19/09/2007*/
  bool NodeHasChildren(long long node_id);

  /** Return the parent id of the node. Add by Mucci 19/09/2007*/
	long long GetNodeParent(long long node_id);
  
	/** Move a node, and its subtree. */
	bool SetNodeParent(long long node_id, long long parent_id );
  
	/** Set the icon for the node. */
  bool SetNodeIcon(long long node_id, int icon);
  
  /** Return the icon index for the node 'node_id'. */
  int  GetNodeIcon(long long node_id);

  /** Select the node. */
  bool SelectNode(long long node_id);

  /** Set the images to be used for the nodes. 
      Must be set before adding any node. 
      The default ImageList provide 4 icons :
      -1 gray dot 
      -2 red dot 
      -3 blue dot 
      -4 yellow dot 
  */
  void SetImageList(wxImageList *img);

  /** Sort the children of node_id. (not the subtree) 
      give node_id = 0 to specify the root. */
  void SortChildren(long long node_id =0);

  /** if autosort is on - the tree is always kept sorted */
  void SetAutoSort(bool enable) {m_Autosort=enable;};

  /** Get the autosort flag. */
  bool GetAutoSort() {return m_Autosort;};

  /** collapse the children of node_id */
  void CollapseNode(long long node_id);

  /** expand the children of node_id */
  void ExpandNode(long long node_id);

	bool IsNodeExpanded(long long node_id);

  /** Set the Listener that will receive event-notification, the Listener can be changed any time  */
  void SetListener(albaObserver *listener)   {m_Listener=listener;}; 

  /** Return the node item from node id. */
  wxTreeItemId ItemFromNode(long long node_id);

  /** Return node id from node item. */
	long long NodeFromItem(wxTreeItemId& item);
  	
  void SetTreeStyle(long style) {m_NodeTree->SetWindowStyle(style);};
  long GetTreeStyle()           {return m_NodeTree->GetWindowStyle();};

	/** Return true if node exist. */
	bool NodeExist(long long node_id);

protected:
  /** Private function that notify the Listener of node selection and deselection. */
  virtual void OnSelectionChanged(wxTreeEvent& event);
  
	/** When tree is used on a wxNotebook m_NodeTree must be called on Sizing . */
  void OnSize(wxSizeEvent& event);
  
	/** Delete recursively a node and its subtree. */
	void DeleteNode2(long long node_id);
  
	/** Move a node, and its subtree. */
  void SetNodeParent2(long long node_id, long long parent_id );
    
  /** Check that id is a valid index in the imagelist - return the (eventually clamped) value */
  int CheckIconId(int icon);

  bool IsRootHidden() {return (GetTreeStyle() & wxTR_HIDE_ROOT) != 0; };

  bool               m_PreventNotify;
  bool               m_Autosort;
	long long          m_NodeRoot;
	albaTreeCtrl      *m_NodeTree;
  wxImageList       *m_NodeImages;       
  wxHashTable       *m_NodeTable;        
  albaObserver       *m_Listener;     

	//----------------------------------------------------------------------------
	// albaGUITreeTableElement:
	/// specialized HashTable element used in albaGUITree to store a reference to a wxTreeItemId 
	//----------------------------------------------------------------------------
	class albaGUITreeTableElement: public wxObject
	{
	public:
	  albaGUITreeTableElement(wxTreeItemId item) {m_TreeItemId=item;  };
		wxTreeItemId GetItem()                 {return m_TreeItemId;};
		void SetItem(wxTreeItemId item){m_TreeItemId=item;  };
	protected:
		wxTreeItemId m_TreeItemId;          
	};

DECLARE_EVENT_TABLE()
}; // end of albaGUITree
#endif
