/*=========================================================================
  Program:   Multimod Application Framework
  Module:    $RCSfile: mmgDialog.cpp,v $
  Language:  C++
  Date:      $Date: 2005-06-10 08:52:57 $
  Version:   $Revision: 1.9 $
  Authors:   Silvano Imboden
==========================================================================
  Copyright (c) 2002/2004
  CINECA - Interuniversity Consortium (www.cineca.it) 
=========================================================================*/


#include "mafDefines.h" 
//----------------------------------------------------------------------------
// NOTE: Every CPP file in the MAF must include "mafDefines.h" as first.
// This force to include Window,wxWidgets and VTK exactly in this order.
// Failing in doing this will result in a run-time error saying:
// "Failure#0: The value of ESP was not properly saved across a function call"
//----------------------------------------------------------------------------

#include "mmgDialog.h"
#include "wx/busyinfo.h"
#include "mafDecl.h"
//----------------------------------------------------------------------------
// Event Table:
//----------------------------------------------------------------------------
BEGIN_EVENT_TABLE(mmgDialog, wxDialog)
  EVT_CLOSE(mmgDialog::nvOnCloseWindow)
  EVT_BUTTON(wxID_OK, mmgDialog::nvOnOK)
  EVT_BUTTON(wxID_CANCEL, mmgDialog::nvOnCancel)
  EVT_BUTTON(wxID_CLOSE, mmgDialog::nvOnClose)
  EVT_BUTTON(wxOK, mmgDialog::nvOnOK)
  EVT_BUTTON(wxCANCEL, mmgDialog::nvOnCancel)

/* todo: discover if the following syntax is valid -- if yes I can have the redefined handler called (if handler are virtual)
  EVT_CLOSE(OnCloseWindow)
  EVT_BUTTON(wxID_OK, OnOK)
  EVT_BUTTON(wxID_CANCEL, OnCancel)
  EVT_BUTTON(wxID_CLOSE, OnClose)
  EVT_BUTTON(wxOK, OnOK)
  EVT_BUTTON(wxCANCEL, OnCancel)
*/
END_EVENT_TABLE()

//----------------------------------------------------------------------------
mmgDialog::mmgDialog(const wxString& title,long style)
: wxDialog()
//----------------------------------------------------------------------------
{
  m_Listener = NULL;
  
  long s = wxCAPTION;
  if(style & mafRESIZABLE) 
    s |= wxRESIZE_BORDER;
  if(style & mafCLOSEWINDOW) 
    s |= wxSYSTEM_MENU;

  Create(mafGetFrame(),-1,title,wxDefaultPosition,wxDefaultSize,s); 

  m_dialog_sizer  =  new wxBoxSizer( wxVERTICAL );
  m_sizer         =  new wxBoxSizer( wxVERTICAL );
  m_buttons_sizer =  NULL;
  m_dialog_sizer->Add(m_sizer,1,wxEXPAND);

  m_ok_button    = NULL;
  m_cancel_button = NULL;
  m_close_button  = NULL;

  // To Paolo -- il sizer vuoto si setta un MinSize arbitrario -->  se non serve non lo metto
  if(style & mafOK || style & mafCANCEL || style & mafCLOSE )
  {
    m_buttons_sizer =  new wxBoxSizer( wxHORIZONTAL );
    m_dialog_sizer->Add(m_buttons_sizer,0,wxCENTRE);
  }
  if( style & mafOK )
  {
    m_ok_button = new wxButton(this,wxID_OK,"ok");
    m_buttons_sizer->Add(m_ok_button,0);
  }
  if( style & mafCANCEL )
  {
    m_cancel_button = new wxButton(this,wxID_CANCEL,"cancel");
    m_buttons_sizer->Add(m_cancel_button ,0);
  }
  if( (style & mafCLOSE) )
  {
    m_close_button = new wxButton(this,wxID_CLOSE,"close");
    m_buttons_sizer->Add(m_close_button ,0);
  }
}
//----------------------------------------------------------------------------
mmgDialog::~mmgDialog( ) 
//----------------------------------------------------------------------------
{
}
//----------------------------------------------------------------------------
int mmgDialog::ShowModal()
//----------------------------------------------------------------------------
{
  m_dialog_sizer->SetMinSize(100,50); // looks ugly when it is empty
  //this->SetAutoLayout( TRUE ); -- not to be called here
  this->SetSizer( m_dialog_sizer );
  //m_dialog_sizer->Fit(this); //-- not to be called, is called by SetSizeHints
  m_dialog_sizer->SetSizeHints(this);
  return wxDialog::ShowModal();
}
//--------------------------------------------------------------------------------
void mmgDialog::OnEvent(mafEventBase *maf_event)
//--------------------------------------------------------------------------------
{
  // POURPOSE:
  // allow wxOK and wxCANCEL generated by a mmgGUI to be considered 
  // like the corresponding events generated by normal buttons.
  if (mafEvent *e = mafEvent::SafeDownCast(maf_event))
  {
    switch(e->GetId())
    {
      case wxID_OK:
      case wxOK:
      {
        wxCommandEvent c(0, wxID_OK);
        OnOK(c);
      }
      break;
      case wxID_CANCEL:
      case wxCANCEL:
      {
        wxCommandEvent c(0, wxID_CANCEL);
        OnCancel(c);  
      }
      break;
      case wxID_CLOSE:
        wxDialog::Close(); // will call OnCloseWindow -- which will call OnCancel
      break;
      default:
        mafEventMacro(*e);
    }
  }
}
//----------------------------------------------------------------------------
void mmgDialog::OnCloseWindow(wxCloseEvent &event)
//----------------------------------------------------------------------------
{
  // --- note about wxDialog::OnCloseWindow
  
  // We'll send a Cancel message by default, which may close the dialog.
  // Check for looping if the Cancel event handler calls Close().

  // Note that if a cancel button and handler aren't present in the dialog,
  // nothing will happen when you close the dialog via the window manager, or
  // via Close(). We wouldn't want to destroy the dialog by default, since
  // the dialog may have been created on the stack. However, this does mean
  // that calling dialog->Close() won't delete the dialog unless the handler
  // for wxID_CANCEL does so. So use Destroy() if you want to be sure to
  // destroy the dialog. The default OnCancel (above) simply ends a modal
  // dialog, and hides a modeless dialog.

  //SIL. 20-4-2005: 
  //So, in normal windows the close buttons destroy the window (Close -> CloseWindow -> Destroy )
  //in dialogs the close button calls Show(false) and don't call Destroy by default.
  //This is reasonable, because the user can call dlg.Show again.

  //So, The close button should call Cancel
  //Cancel should not destroy the window - just hide it
  //To know when the window is destroyed - override Destroy.

  wxDialog::OnCloseWindow(event);
}
//----------------------------------------------------------------------------
void mmgDialog::OnOK(wxCommandEvent &event)
//----------------------------------------------------------------------------
{
  wxDialog::OnOK(event);
  /* --- this is what wxDialog::OnOK does
   this is what is done 
  if ( Validate() && TransferDataFromWindow() )
  {
    SetReturnCode(wxID_OK);  
    Show(false);
  }
  Note that the Window just hidden, is not destroyed.  
  */
}
//----------------------------------------------------------------------------
void mmgDialog::OnCancel(wxCommandEvent &event)
//----------------------------------------------------------------------------
{
  wxDialog::OnCancel(event);
  /* --- this is what wxDialog::OnCancel does
  SetReturnCode(wxID_CANCEL);
  Show(false);
  Note that the Window just hidden, is not destroyed.  
  */
}
