/*=========================================================================
  Program:   Multimod Application Framework
  Module:    $RCSfile: mafOpVOIDensityEditor.h,v $
  Language:  C++
  Date:      $Date: 2008-12-10 14:29:36 $
  Version:   $Revision: 1.1.2.1 $
  Authors:   Matteo Giacomoni & Paolo Quadrani
==========================================================================
  Copyright (c) 2002/2004
  CINECA - Interuniversity Consortium (www.cineca.it) 
=========================================================================*/

#ifndef __mafOpVOIDensityEditor_H__
#define __mafOpVOIDensityEditor_H__

//----------------------------------------------------------------------------
// Includes :
//----------------------------------------------------------------------------
#include "mafOp.h"
#include "mafVME.h"

//----------------------------------------------------------------------------
// forward references :
//----------------------------------------------------------------------------
class mafNode;
class vtkDataSet;

//----------------------------------------------------------------------------
// mafOpVOIDensityEditor :
//----------------------------------------------------------------------------
/** This class accepts mafVMEVolumeGray as input and take a surface as additional
input, then change the scalar density of the volumes' voxels inner the surface with
a density value given by the user. This operation is used in general after that a
mafVMEVolumeGray is generated by the mafOpCreateVolume operation.

@sa mafOpCreateVolume, mafVMEVolumeGray
*/
class mafOpVOIDensityEditor: public mafOp
{
public:
	mafOpVOIDensityEditor(const wxString &label = "VOIDensityEditor");
	~mafOpVOIDensityEditor(); 
	virtual void OnEvent(mafEventBase *maf_event);
  
  mafTypeMacro(mafOpVOIDensityEditor, mafOp);

  /** return a copy of itself, this needs to put the operation into the undo stack. */
	mafOp* Copy();
	
	/** Return true for the acceptable vme type. */
	bool Accept(mafNode* Node);

	/** Set the input vme for the operation. */
	void OpRun();

  /** Execute the editing of the input voulme density region.*/
  void OpDo();

	/** Retrieve the previous state of the input VME. */
	void OpUndo();

	/**	Set surface of input in test mode*/
	void SetSurface(mafNode *Surface){m_Surface=Surface;};

  /** Scalar value used to fill volume region defined by the surface.*/
  void SetScalarValue(double fillScalar) {m_ScalarValue = fillScalar;};

  /** Get the scalar value used to fill volume region defined by the surface.*/
  double GetScalarValue() {return m_ScalarValue;}

  /** Change scalar density of the input volume that are inside the chosen surface with the given m_ScalarValue.*/
	void EditVolumeScalars();

 	static bool OutputSurfaceAccept(mafNode* Node) {return(Node != NULL && (((mafVME *)Node)->GetOutput()->IsA("mafVMEOutputSurface")));};

protected:
  mafNode *m_Surface; ///< Surface used to define the VOI in which write the constant density value.
  double   m_ScalarValue; ///< Scalar value that will fill the volume's voxel.
  double   m_CurrentTimestamp; ///< Timestamp of the input VME.
  vtkDataSet *m_OldData; ///< Volume data before the editing (used by the Undo mechanism).
};
#endif
