/*=========================================================================
  Program:   Multimod Application Framework
  Module:    $RCSfile: mmoLandmarkExporter.h,v $
  Language:  C++
  Date:      $Date: 2006-10-05 08:44:58 $
  Version:   $Revision: 1.1 $
  Authors:   Paolo Quadrani, Daniele Giunchi (porting MAf 2.0)
==========================================================================
Copyright (c) 2002/2004
CINECA - Interuniversity Consortium (www.cineca.it) 
=========================================================================*/

#ifndef __mmoLandmarkExporter_H__
#define __mmoLandmarkExporter_H__

//----------------------------------------------------------------------------
// Include :
//----------------------------------------------------------------------------
#include "mafOp.h"


//----------------------------------------------------------------------------
// forward references :
//----------------------------------------------------------------------------
class mafEvent;
class mafVMEGroup;
class mafVME;

//----------------------------------------------------------------------------
// mmoLandmarkExporter :
//----------------------------------------------------------------------------
/** Exporter for the landmark coordinates: the data are exported in ASCII format. 
Each raw represents a landmark and contains the (x,y,z) coordinate.*/
class mmoLandmarkExporter: public mafOp
{
public:
	mmoLandmarkExporter(wxString label);
	~mmoLandmarkExporter(); 
	mafOp* Copy();

	/** Return true for the acceptable vme type. */
	bool Accept(mafNode *node);

	/** Build the interface of the operation, i.e the dialog that let choose the name of the output file. */
	void OpRun();

  void ExportLandmark();
	/** Execute the operation: save landmark position. */
	//void OpDo();

	/** This method is called at the end of the operation and result contain the wxOK or wxCANCEL. */
	//void OpStop(int result);

	/** Undo the operation. */
	//void OpUndo();

	/** Deal with the events generated by the user interface. */
	//void OnEvent(mafEvent& e);

  /** Set the filename for the .stl to export */
  void SetFileName(const char *file_name) {m_File = file_name;};

protected:
	wxString	m_File;
	wxString	m_FileDir;
	mafVME*		m_Vme; 
	bool*		m_State;			

};
#endif













