/*=========================================================================

 Program: ALBA (Agile Library for Biomedical Applications)
 Module: albaOpExporterImagesTest
 Authors: Roberto Mucci
 
 Copyright (c) BIC
 All rights reserved. See Copyright.txt or


 This software is distributed WITHOUT ANY WARRANTY; without even
 the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 PURPOSE.  See the above copyright notice for more information.

=========================================================================*/

#include "albaDefines.h" 
//----------------------------------------------------------------------------
// NOTE: Every CPP file in the ALBA must include "albaDefines.h" as first.
// This force to include Window,wxWidgets and VTK exactly in this order.
// Failing in doing this will result in a run-time error saying:
// "Failure#0: The value of ESP was not properly saved across a function call"
//----------------------------------------------------------------------------

#include <cppunit/config/SourcePrefix.h>
#include "albaOpExporterImages.h"

#include "albaOpExporterImagesTest.h"
#include "albaOpImporterImage.h"
#include "albaOpImporterVTK.h"

#include "albaString.h"
#include "albaVMEStorage.h"
#include "albaVMERoot.h"
#include "albaVMEVolumeGray.h"
#include "albaVMEImage.h"
#include "albaVMEOutputSurface.h"

#include "vtkImageMathematics.h"
#include "vtkALBASmartPointer.h"
#include "vtkImageData.h"
#include "vtkImageData.h"
#include "vtkPointData.h"
#include "vtkPNGWriter.h"
#include "wx/dir.h"


void albaOpExporterImagesTest::TestFixture()
{
}

//-----------------------------------------------------------
void albaOpExporterImagesTest::TestConstructor()
{
  albaOpExporterImages *exporter = new albaOpExporterImages("exporter bmp");
  albaDEL(exporter);
}

//-----------------------------------------------------------
void albaOpExporterImagesTest::TestExportBMP()
{
	TestExport(albaOpExporterImages::BMP);
}

//-----------------------------------------------------------
void albaOpExporterImagesTest::TestExportTIFF()
{
	//Test disabled for a bug in vtkTIFFWriter in VTK 4.4
	//TestExport(albaOpExporterImages::TIFF);
}

//-----------------------------------------------------------
void albaOpExporterImagesTest::TestExportPNG()
{
	TestExport(albaOpExporterImages::PNG);
}

//-----------------------------------------------------------
void albaOpExporterImagesTest::TestExportJPEG()
{
	TestExport(albaOpExporterImages::JPEG);
}

//----------------------------------------------------------------------------
void albaOpExporterImagesTest::TestExport(int fileFormat)
{
	//Initialize storage
	albaVMEStorage *storage = albaVMEStorage::New();
  storage->GetRoot()->SetName("root");
  storage->GetRoot()->Initialize();

	//Import the VTK Volume generated by the Original image files
	albaOpImporterVTK *importerVTK = new albaOpImporterVTK("importer");
  importerVTK->TestModeOn();
  importerVTK->SetInput(storage->GetRoot());
  albaString filename = ALBA_DATA_ROOT;
  filename << "/Test_ExporterImages/VolTestImages.vtk";
  importerVTK->SetFileName(filename.GetCStr());
  importerVTK->ImportFile();

	albaVMEVolumeGray *vmeVolumeGrayImported = albaVMEVolumeGray::SafeDownCast(importerVTK->GetOutput());
	vmeVolumeGrayImported->Update();

	//delete the directory where the image files will be exported
	albaString filenameDir = GET_TEST_DATA_DIR();
	
	// Remove directory if it exists
	wxString dirPath(filenameDir.GetCStr());
	if (wxDir::Exists(dirPath))
	{
		wxString filename;
    wxDir dir(dirPath);
		bool cont = dir.GetFirst(&filename, wxEmptyString, wxDIR_FILES);
		while (cont)
		{
			wxString fullPath = dirPath + wxFILE_SEP_PATH + filename;
			wxRemoveFile(fullPath);
			cont = dir.GetNext(&filename);
		}
		wxRmdir(dirPath);
	}

  wxMkDir(dirPath);

	//Initialize exporter and export the stack of images
	albaOpExporterImages *exporter = new albaOpExporterImages();
	exporter->TestModeOn();
	exporter->SetInput(vmeVolumeGrayImported);
	exporter->SetDirName(filenameDir);
	exporter->SetFileFormat((albaOpExporterImages::FileFormat)fileFormat);
	exporter->SaveImages();

	//Import the central image file generated by the exporter
	wxString ext;
	switch (fileFormat)
	{
	case albaOpExporterImages::BMP:
		ext << "bmp";
		break;
	case albaOpExporterImages::JPEG:
		ext << "jpeg";
		break;
	case albaOpExporterImages::PNG:
		ext << "png";
		break;
	case albaOpExporterImages::TIFF:
		ext << "tiff";
		break;
	}

	albaOpImporterImage *importerBMP = new albaOpImporterImage();
  albaString filenameExporter = filenameDir;
	filenameExporter << "\\VolTestImages_1024x1024_0002." << ext;


  importerBMP->TestModeOn();
  importerBMP->SetInput(storage->GetRoot());
  importerBMP->SetBuildVolumeFlag(false);
  importerBMP->AddFileName(filenameExporter);
  importerBMP->Import();
  
  albaVMEImage *vmeImageExported = albaVMEImage::SafeDownCast(importerBMP->GetOutput()->GetChild(0));
  vmeImageExported->Update();

  //cast the albaVMEImage to a vtkImagedata to compare it with the original one
  vtkImageData  *dataExported;
  dataExported = vmeImageExported->GetImageOutput()->GetImageData();
  

  //Import the central image of the original bmp files from wich the volume has been created
	albaOpImporterImage *importerImageOriginal = new albaOpImporterImage("importer");
  albaString filenameOriginal = ALBA_DATA_ROOT;
	
	filenameOriginal << "/Test_ExporterImages/Image_02." << ext;

	importerImageOriginal->TestModeOn();
	importerImageOriginal->SetBuildVolumeFlag(false);
	importerImageOriginal->SetInput(storage->GetRoot());
	importerImageOriginal->AddFileName(filenameOriginal);
	importerImageOriginal->Import();

	albaVMEImage *vmeImageOriginal = albaVMEImage::SafeDownCast(importerImageOriginal->GetOutput()->GetChild(0));
	vmeImageOriginal->Update();

 //cast the albaVMEImage to a vtkImagedata to compare it with the one generated by the exporter
	vtkImageData *dataOriginal;
  dataOriginal = vmeImageOriginal->GetImageOutput()->GetImageData();

  //SetOperationToSubtract subtract one image from the other one: the result 
  //image must be a black image, with all the scalars set to zero
  vtkImageData *imageFinal;
  vtkALBASmartPointer<vtkImageMathematics> math;
  math->SetInput1Data(dataOriginal);
  math->SetInput2Data(dataExported);
  math->SetOperationToSubtract();
  math->Update();
  imageFinal = math->GetOutput();

  int points = imageFinal->GetPointData()->GetNumberOfTuples();
	CPPUNIT_ASSERT(points > 0);
	
  double sr[2];
	imageFinal->GetScalarRange(sr);

	if (sr[0] != 0 || sr[1] != 0)
	{
		vtkPNGWriter *imageWriter;
		vtkNEW(imageWriter);
		
		albaString filenameDiff = filenameDir;
		filenameDiff << "\\ImageDiff_02.png";

		imageWriter->SetInputConnection(math->GetOutputPort());
		imageWriter->SetFileName(filenameDiff.GetCStr());
		imageWriter->Write();
		vtkDEL(imageWriter);

		albaLogMessage("CompareImages has found differences. File %s stored.", filenameDiff.GetCStr());

		CPPUNIT_ASSERT(sr[0] == 0 && sr[1] == 0);
	}


  vmeVolumeGrayImported = NULL;
  vmeImageExported = NULL;
  vmeImageOriginal = NULL;

  albaDEL(vmeImageExported);
  albaDEL(importerBMP);
	albaDEL(importerImageOriginal);

  albaDEL(exporter);
  vtkDEL(importerVTK);
  albaDEL(storage);
}
